# Generated by Django 5.0 on 2024-01-10 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_remove_snippet_owner_snippet_foobar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='foobar',
        ),
    ]
